language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: cS0GihjyyTcDleM2Xt0XkyJH9sa5rIILK3psUjnyjl8yyPH5JZ36Iq3p1UG633NYtzqjM+fNp8L1UE3f+5N4CcN6GflsSdcn63lOmgffITZfNP98W586a0a1/mUqOhbAgXM52YupW/UEHGxBcofj1I/LMJwIHtfH9Djj4L6kwtA=
  - secure: cNzRxsVYRP4mHhpDq7bG1y2VeOh+xTuV38v0BCReG5BP7DRvaUacIIwJ7ltKQ8fK6Fc3tevBGfQONw3AO4C/rnbkb6Co7kPx1/3PzDLRC28ro12/oxceYPS6ySkMhYu+POe5dgzAIINtU9h9DDxuToRhqTcUjyEcZUFr4cF09eA=
  - secure: ZH5zRjrBUsqHq86L1Ek3C2PQe1KZBFUX+rM0oatfV+us6wg8Za+FMm6XfwCpM/zj3QJ/57Jb8TZYMxnAgbzK9ViJ4q7LDmEWgn3U7Sce+W/QD+dpLu3FulVcMf4EsRThNK7O2K+qzvQUOAGBmDF9FOow8fHWRs6VSozFlNsJui8=
  - secure: mFQ9vyiOEeWS/kdJN+5SmQv8pFtcGVavIqKWtrQDQnh2cWsvEN+Ak1OHSSdGOtuXDMjRr4YXk363FVJcWGUBwCBy2N0W2rVTKTs6qcghgYeroEty/EQiXY+pDaqHTAXYM6dWfDK+lLxGJDVQCctLWyrFA7yQer2gxNehUfZUFps=
